### ISSUE TITLE
ImportError: cannot import name 'QtWebKitWidgets' from 'PyQt5' 

### ISSUE THREAD

**Issue by Smo-RBR** [QGIS-Contribution/QGIS-ResourceSharing#273]
MacOS 12.5.1 QGis installed via Macports

Would be glad if someone can give me a hint. As i understand, QTWebkit has been removed, so we should use QTWebengine. Installed this, but, it still doesnt help.

```
QGIS-Version | 3.26.2-Buenos Aires | QGIS-Codezweig | Release 3.26
-- | -- | -- | --
Qt-Version | 5.15.5
Python-Version | 3.10.6
GDAL-Version | 3.4.3
PROJ-Version | 8.2.1
EPSG-Registraturdatenbankversion | v10.041 (2021-12-03)
GEOS-Version | 3.11.0-CAPI-1.17.0
SQLite-Version | 3.39.2
PDAL-Version | 2.4.2
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.3
BS-Version | macOS 12.5
  |   |   |  
Aktive Python-Erweiterungen
QuickOSM | 2.1.1
quick_map_services | 0.19.29
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
```

```
ImportError: cannot import name 'QtWebKitWidgets' from 'PyQt5' (/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/__init__.py) 
Traceback (most recent call last):
  File "/Applications/MacPorts/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Volumes/Smo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/__init__.py", line 54, in classFactory
    from qgis_resource_sharing.plugin import ResourceSharingPlugin
  File "/Applications/MacPorts/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Volumes/Smo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/plugin.py", line 33, in 
    from qgis_resource_sharing.gui.resource_sharing_dialog import ResourceSharingDialog
  File "/Applications/MacPorts/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Volumes/Smo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/gui/resource_sharing_dialog.py", line 71, in 
    FORM_CLASS, _ = uic.loadUiType(str(ui_path("resource_sharing_dialog_base.ui")))
  File "/Applications/MacPorts/QGIS3.app/Contents/MacOS/../Resources/python/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/uic/__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 290, in 
ImportError: cannot import name 'QtWebKitWidgets' from 'PyQt5' (/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/__init__.py)


Python-Version: 3.10.6 (main, Aug  3 2022, 03:22:45) [Clang 13.0.0 (clang-1300.0.29.30)] 
QGIS-Version: 3.26.2-Buenos Aires Buenos Aires, exported 

Python-Pfad:
/Applications/MacPorts/QGIS3.app/Contents/MacOS/../Resources/python
/Volumes/Smo/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Volumes/Smo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/MacPorts/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python310.zip
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
/Volumes/Smo/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Volumes/Smo/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs`
```

**Comment by dgva** [comment]
I also have this, on EndeavourOS. 



QGIS version | 3.28.1-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.7
Python version | 3.10.8
GDAL/OGR version | 3.6.0
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
Compiled against GEOS | 3.11.0-CAPI-1.17.0 | Running against GEOS | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.0
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.3
OS version | EndeavourOS
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
CalculateGeometry | 0.6.8
changeDataSource | 3.1
quick_map_services | 0.19.32
LAStools | 1.4
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
grassprovider | 2.12.99

</body></html>QGIS version
3.28.1-Firenze
QGIS code branch
[Release 3.28](https://github.com/qgis/QGIS/tree/release-3_28)
Qt version
5.15.7
Python version
3.10.8
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
Compiled against GEOS
3.11.0-CAPI-1.17.0
Running against GEOS
3.11.1-CAPI-1.17.1
SQLite version
3.40.0
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.13.3
OS version
EndeavourOS




Active Python plugins
FreehandRasterGeoreferencer
0.8.3
CalculateGeometry
0.6.8
changeDataSource
3.1
quick_map_services
0.19.32
LAStools
1.4
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
grassprovider
2.12.99

**Comment by nanounanue** [comment]
Same problem, any ideas?
