### ISSUE TITLE
No host specified

### ISSUE THREAD

**Issue by mercerraa** [QGIS-Contribution/QGIS-ResourceSharing#332]
### What is the bug or the crash?

Install returns "Error: No host specified." for all collections. 
Oddly the uninstall "works", returning "The collection was successfully uninstalled" despite nothing having been installed to begin with.

### Steps to reproduce the issue

Click on Install. 

### Versions

QGIS Resource Sharing 1.0.0
QGIS 3.36.2 (cannot test on LTR as this now crashes on Windows 11)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Folder name:  \AppData\Roaming\QGIS\QGIS3\profiles\Name\resource_sharing

**Comment by KyleMercer** [comment]
Exact same issue for me.

**Comment by Guts** [comment]
Hello @mercerraa and @KyleMercer ,

Can you try to install the experimental version please and let me know if you can reproduce?

**Comment by KyleMercer** [comment]
Installed 3.37.0 Nightly Build (May 8) and same error message. Here is the debug output from the addon:

```
2024-05-13T16:39:38     WARNING    Traceback (most recent call last):
              File "C:\Users/User1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\repository_handler\remote_git_handler.py", line 157, in download_collection
              porcelain.pull(
              File "C:\Users\User1\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs\dulwich\porcelain.py", line 1182, in pull
              fetch_result = client.fetch(
              ^^^^^^^^^^^^^
              File "C:\Users\User1\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs\dulwich\client.py", line 824, in fetch
              result = self.fetch_pack(
              ^^^^^^^^^^^^^^^^
              File "C:\Users\User1\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs\dulwich\client.py", line 2107, in fetch_pack
              resp, read = self._smart_request(
              ^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\User1\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs\dulwich\client.py", line 1983, in _smart_request
              resp, read = self._http_request(url, headers, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\User1\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs\dulwich\client.py", line 2212, in _http_request
              resp = self.pool_manager.request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.0\apps\Python312\Lib\site-packages\urllib3\_request_methods.py", line 144, in request
              return self.request_encode_body(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.0\apps\Python312\Lib\site-packages\urllib3\_request_methods.py", line 279, in request_encode_body
              return self.urlopen(method, url, **extra_kw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.0\apps\Python312\Lib\site-packages\urllib3\poolmanager.py", line 433, in urlopen
              conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.0\apps\Python312\Lib\site-packages\urllib3\poolmanager.py", line 295, in connection_from_host
              raise LocationValueError("No host specified.")
             urllib3.exceptions.LocationValueError: No host specified.
             

```

**Comment by Guts** [comment]
I meant the experimental version of the plugin, not of QGIS. Sorry for the _quiproquo_.

**Comment by mercerraa** [comment]
The problem is still there with 1.1.0-beta1 downloaded from the plugins site and installed from zip on QGIS 3.36.2

**Comment by mercerraa** [comment]
Log from error:
2024-05-14T09:07:20     WARNING    Traceback (most recent call last):
              File "C:\Users/USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\Test/python/plugins\qgis_resource_sharing\repository_handler\remote_git_handler.py", line 119, in download_collection
              repo = porcelain.clone(
              ^^^^^^^^^^^^^^^^
              File "C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\Test\python\plugins\qgis_resource_sharing\ext_libs\dulwich\porcelain.py", line 445, in clone
              message=message,
              File "C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\Test\python\plugins\qgis_resource_sharing\ext_libs\dulwich\client.py", line 747, in clone
              b"fetch",
              File "C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\Test\python\plugins\qgis_resource_sharing\ext_libs\dulwich\client.py", line 824, in fetch
              dir=getattr(target.object_store, "path", None),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\Test\python\plugins\qgis_resource_sharing\ext_libs\dulwich\client.py", line 2107, in fetch_pack
              File "C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\Test\python\plugins\qgis_resource_sharing\ext_libs\dulwich\client.py", line 1983, in _smart_request
              self.dumb = dumb
              ^^^^
              File "C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\Test\python\plugins\qgis_resource_sharing\ext_libs\dulwich\client.py", line 2212, in _http_request
              File "C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\urllib3\_request_methods.py", line 144, in request
              return self.request_encode_body(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\urllib3\_request_methods.py", line 279, in request_encode_body
              return self.urlopen(method, url, **extra_kw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\urllib3\poolmanager.py", line 433, in urlopen
              conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\urllib3\poolmanager.py", line 295, in connection_from_host
              raise LocationValueError("No host specified.")
             urllib3.exceptions.LocationValueError: No host specified.

**Comment by Guts** [comment]
In the mean time, @mercerraa you can try with the packaged version attached to the GH release https://github.com/QGIS-Contribution/QGIS-ResourceSharing/releases/tag/1.1.0

**Comment by KyleMercer** [comment]
Installed 1.1.0-beta1 of the plugin and same error occurs.

**Comment by KyleMercer** [comment]
I installed the version from Github and the problem has been solved. I did have a small issue with the maximum version defined in the metadata.txt not being 3.36.2 but once I changed it and enabled the plugin again I was able to load shared resources.

Thanks @Guts

**Comment by vmgencheva** [comment]
Tested with zip file from GH + QGIS 3.34.7 same error; also tested the beta from here: https://plugins.qgis.org/plugins/qgis_resource_sharing/version/1.1.0-beta1/ - same error; @KyleMercer with which QGIS version did you get it to work?

**Comment by KyleMercer** [comment]
I got the beta version to work with QGIS 3.36.2

**Comment by rpansare** [comment]
I got the GH version to work with 3.38. Changed the maximum version just like @KyleMercer .

**Comment by cancerfist** [comment]
having this issue again with 3.36.3

have tried 1.0, 1.0.1 and the Beta version. none are working.
