### ISSUE TITLE
Can't run (or install) the plugin if ~/QGIS/Resource Sharing doesn't exist

### ISSUE THREAD

**Issue by borysiasty** [QGIS-Contribution/QGIS-ResourceSharing#43]
I couldn't run the plugin after removing `~/QGIS/Resource Sharing`. I had to re-create the directory manually prior to loading the plugin.

```
Traceback (most recent call last):
  File "/home/borys/sources/qgis/build-2_18/output/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/borys/.qgis2/python/plugins/qgis_resource_sharing/__init__.py", line 58, in classFactory
    return Plugin(iface)
  File "/home/borys/.qgis2/python/plugins/qgis_resource_sharing/resource_sharing/plugin.py", line 61, in __init__
    self.dlg = ResourceSharingDialog(iface=self.iface)
  File "/home/borys/.qgis2/python/plugins/qgis_resource_sharing/resource_sharing/gui/resource_sharing_dialog.py", line 140, in __init__
    self.repository_manager = RepositoryManager()
  File "/home/borys/.qgis2/python/plugins/qgis_resource_sharing/resource_sharing/repository_manager.py", line 72, in __init__
    self.load_repositories()
  File "/home/borys/.qgis2/python/plugins/qgis_resource_sharing/resource_sharing/repository_manager.py", line 358, in load_repositories
    self.rebuild_collections()
  File "/home/borys/.qgis2/python/plugins/qgis_resource_sharing/resource_sharing/repository_manager.py", line 325, in rebuild_collections
    self._collections_manager.uninstall(collection_id)
  File "/home/borys/.qgis2/python/plugins/qgis_resource_sharing/resource_sharing/collection_manager.py", line 169, in uninstall
    resource_handler_instance.uninstall()
  File "/home/borys/.qgis2/python/plugins/qgis_resource_sharing/resource_sharing/resource_handler/svg_handler.py", line 55, in uninstall
    collection_directories = os.listdir(local_collection_path())
OSError: [Errno 2] No file or directory: '/home/borys/QGIS/Resource Sharing'

```
By the way, what about using the existing ~/.qgis2/resource_sharing rather than creating an additional top-level subdirectory in the homedir?

**Comment by havatv** [comment]
Thanks for reporting, @borysiasty!
I have tried to reproduce the issue with version 0.9.0 of the plugin (QGIS 3.4.15 on Ubuntu 18.04), but the plugin starts (and works) without issues.

On what platforms have you experienced this problem, and with what version of QGIS and the plugin?

It would be great if you could check if the problem persists with the latest plugin version of the plugin.

**Comment by borysiasty** [comment]
Ah, it was years ago! Now I can't reproduce it as well. Thanks for revising that old stuff :)

**Comment by havatv** [comment]
Thanks, @borysiasty! Your input has been valuable in the development of the plugin.

**Comment by havatv** [comment]
I have found a way to reproduce this problem with version 0.9.0 of the plugin.
1. Start QGIS 3.10
1. Install version 0.9.0 of the plugin
2. Start the plugin, reload repositories and install a collection - this will create the `~/QGIS/Resource Sharing` directory with one subdirectory containing the installed collection, and also create `<QGIS_user_home>/Resource Sharing` (`~/.local/share/QGIS/QGIS3/profiles/default/Resource Sharing`on Ubuntu) with the `repositories` subdirectory and `repositories_cache`.
3. Close the plugin and exit QGIS
4. Remove the`~/QGIS/Resource Sharing` directory
5. Start QGIS, and a dialog box with an error appears:

>     Couldn't load plugin 'qgis_resource_sharing' due to an error when calling its classFactory() method
>     ...

6. Exit QGIS
7. Remove `<QGIS_user_home>/Resource Sharing`
8. Start QGIS 3.10 - it will start as normal (no error message)
8. Start the plugin, reload repositories and install a collection - this will create the `~/QGIS/Resource Sharing` directory with one subdirectory containing the installed collection

So the issue arises if the `~/QGIS/Resource Sharing` directory is removed without also removing the cache and repositories (under `<QGIS_user_home>/Resource Sharing`).
