### ISSUE TITLE
classFactory() error

### ISSUE THREAD

**Issue by chleidersdorff** [QGIS-Contribution/QGIS-ResourceSharing#64]
I get the following error when trying to install this plugin through QGIS 3 plugin manager. I am on 3.10.2-A Coruña:
```
Couldn't load plugin 'qgis_resource_sharing' due to an error when calling its classFactory() method 

AttributeError: 'NoneType' object has no attribute 'strip' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\__init__.py", line 56, in classFactory
    return Plugin(iface)
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\plugin.py", line 65, in __init__
    self.dlg = ResourceSharingDialog(iface=self.iface)
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\gui\resource_sharing_dialog.py", line 156, in __init__
    self.repository_manager = RepositoryManager()
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\repository_manager.py", line 68, in __init__
    self.fetch_online_directories()
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\repository_manager.py", line 97, in fetch_online_directories
    self._online_directories[row['name']] = row['url'].strip()
AttributeError: 'NoneType' object has no attribute 'strip'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.2-A Coruña A Coruña, 616ad4531b 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\christianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\christianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\christianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
```

**Comment by elpaso** [comment]
Which version of the plugin?

**Comment by chleidersdorff** [comment]
I installed the latest version through the plugin manager. And downloaded the latest github version too to try. Both cause the same error.

**Comment by Geojim** [comment]
Same here.
0.8.0 with QGIS 3.10.1, python 3.7.0, w10x64

**Comment by havatv** [comment]
Thanks for reporting, @chleidersdorff.
I can not reproduce with QGIS 3.4 or QGIS 3.10 on Ubuntu 18.04, nor with QGIS 3.4 on Windows 10x64. I only have the "officially approved" repositories.
It could be a problem with the loading of repositories, so it would be interesting to know if you have added repositories, and if so, which (URL).

**Comment by havatv** [comment]
#82 should protect against this error situation. It did not make it into 0.10.0, so testing must currently be done with the ``develop`` branch.
Problems with directory entries should be reported, so that they can be fixed.

**Comment by havatv** [comment]
#82 is included in 0.11.0, that has just been uploaded to plugins.org.

**Comment by chleidersdorff** [comment]
Still getting an error when trying to install "Exception: Missing URL for repository"

see below for all details:

Couldn't load plugin 'qgis_resource_sharing' due to an error when calling its classFactory() method 

Exception: Missing URL for repository '' - not added 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\__init__.py", line 56, in classFactory
    return Plugin(iface)
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\plugin.py", line 65, in __init__
    self.dlg = ResourceSharingDialog(iface=self.iface)
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\gui\resource_sharing_dialog.py", line 158, in __init__
    self.repository_manager = RepositoryManager()
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\repository_manager.py", line 69, in __init__
    self.fetch_online_directories()
  File "C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing\resource_sharing\repository_manager.py", line 113, in fetch_online_directories
    "' - not added")
Exception: Missing URL for repository '' - not added


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.0-București București, cd141490ec 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/christianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\christianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\christianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\christianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs

**Comment by havatv** [comment]
Thanks for testing, @chleidersdorff !
My mistake - I used an exception to avoid the exception...
I will try another solution.

**Comment by havatv** [comment]
@chleidersdorff, I have tried again with a new PR (not yet merged).
It would be great if you could test the latest it to determine if it works for you:
1. download: https://github.com/QGIS-Contribution/QGIS-ResourceSharing/archive/havatv-log_level.zip
2. unzip in your plugin directory
3. remove the directory with your current Resource Sharing plugin
4. (re)start QGIS
5. enable the plugin in the plugin manager
6. run

**Comment by chleidersdorff** [comment]
yep that one works :)

**Comment by havatv** [comment]
Thanks for testing, @chleidersdorff! 
I will merge and close this issue.
